/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BookingForm: typeof import('./src/components/BookingForm.vue')['default']
    BookingList: typeof import('./src/components/BookingList.vue')['default']
    Datepicker: typeof import('./src/components/Elcomponents/Datepicker.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElComponent: typeof import('./src/components/Elcomponents/ElComponent.vue')['default']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    RoomForm: typeof import('./src/components/RoomForm.vue')['default']
    RoomList: typeof import('./src/components/RoomList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Schedule: typeof import('./src/components/Schedule.vue')['default']
  }
}
